### ISSUE TITLE
Not working with webpack 4

### ISSUE THREAD

**Issue by Harrix** [AnujRNair/webpack-extraneous-file-cleanup-plugin#8]
Not working with webpack 4

```
TypeError: Cannot read property 'files' of undefined
    at Stats.toJson (D:\Harrix\GitHub\Harrix-HTML-Template\node_modules\webpack\lib\Stats.js:368:31)
    at Stats.toString (D:\Harrix\GitHub\Harrix-HTML-Template\node_modules\webpack\lib\Stats.js:627:20)
    at compilerCallback (D:\Harrix\GitHub\Harrix-HTML-Template\node_modules\webpack-cli\bin\webpack.js:484:32)
    at hooks.done.callAsync.err (D:\Harrix\GitHub\Harrix-HTML-Template\node_modules\webpack\lib\Compiler.js:185:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\Harrix\GitHub\Harrix-HTML-Template\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (D:\Harrix\GitHub\Harrix-HTML-Template\node_modules\tapable\lib\Hook.js:35:21)
    at emitRecords.err (D:\Harrix\GitHub\Harrix-HTML-Template\node_modules\webpack\lib\Compiler.js:183:22)
    at Compiler.emitRecords (D:\Harrix\GitHub\Harrix-HTML-Template\node_modules\webpack\lib\Compiler.js:295:39)
    at emitAssets.err (D:\Harrix\GitHub\Harrix-HTML-Template\node_modules\webpack\lib\Compiler.js:177:10)
    at hooks.afterEmit.callAsync.err (D:\Harrix\GitHub\Harrix-HTML-Template\node_modules\webpack\lib\Compiler.js:281:14)
    at _err1 (eval at create (D:\Harrix\GitHub\Harrix-HTML-Template\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:25:1)
    at callback (D:\Harrix\GitHub\Harrix-HTML-Template\node_modules\copy-webpack-plugin\dist\index.js:126:17)
    at afterEmit (D:\Harrix\GitHub\Harrix-HTML-Template\node_modules\copy-webpack-plugin\dist\index.js:220:13)
    at _err0 (eval at create (D:\Harrix\GitHub\Harrix-HTML-Template\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:12:1)
    at compiler.plugin (D:\Harrix\GitHub\Harrix-HTML-Template\node_modules\webpack-extraneous-file-cleanup-plugin\lib\plugin.js:119:5)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\Harrix\GitHub\Harrix-HTML-Template\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (D:\Harrix\GitHub\Harrix-HTML-Template\node_modules\tapable\lib\Hook.js:35:21)
    at asyncLib.forEach.err (D:\Harrix\GitHub\Harrix-HTML-Template\node_modules\webpack\lib\Compiler.js:278:27)
    at done (D:\Harrix\GitHub\Harrix-HTML-Template\node_modules\neo-async\async.js:2809:11)
    at D:\Harrix\GitHub\Harrix-HTML-Template\node_modules\neo-async\async.js:2760:7
    at D:\Harrix\GitHub\Harrix-HTML-Template\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:153:20)
```

**Comment by MarkSky** [comment]
I use webpack 4.4.1, it still created small js files.

**Comment by AnujRNair** [comment]
This should now be solved with the merge of https://github.com/AnujRNair/webpack-extraneous-file-cleanup-plugin/pull/9 and the release of 2.0.0
